dbt_class:
  outputs:
    dev:
      dbname:
      - dbname
      host:
      - host
      pass:
      - dev_password
      port:
      - port
      schema:
      - dev_schema
      threads: 1 or more
      type: postgres
      user:
      - dev_username
    prod:
      dbname:
      - dbname
      host:
      - host
      pass:
      - prod_password
      port:
      - port
      schema:
      - prod_schema
      threads: 1 or more
      type: postgres
      user:
      - prod_username
  target: dev
dbt_class_project:
  outputs:
    dev:
      dbname: ada
      host: localhost
      pass: ada
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: ada
      host: localhost
      pass: ada
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
dbt_project:
  outputs:
    dev:
      dbname: ada
      host: localhost
      pass: ada
      port: 5432
      schema: public
      threads: 1 or more
      type: postgres
      user: postgres
    prod:
      dbname:
      - dbname
      host:
      - host
      pass:
      - prod_password
      port:
      - port
      schema:
      - prod_schema
      threads: 1 or more
      type: postgres
      user:
      - prod_username
  target: dev
exemplo_aula_hoje:
  outputs:
    dev:
      dbname: ada
      host: localhost
      pass: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
exemplo_dbt:
  outputs:
    dev:
      dbname: ada
      host: localhost
      pass: postgres
      port: 5432
      schema: ada
      threads: 1
      type: postgres
      user: postgres
  target: dev
airbnb_project:
  outputs:
    dev:
      dbname: ada
      host: localhost
      pass: ada
      port: 5432
      schema: airbnb
      threads: 1
      type: postgres
      user: postgres