version: 2


models:
  - name: autos_silver
    columns:
      - name: avg_price
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 500000
      - name: avg_power_ps
        tests:
          - not_null
      - name: avg_kilometer
        tests:
          - not_null